import type { Metadata } from 'next';
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs';
import { getMessages } from 'next-intl/server';
import { Inter } from 'next/font/google';
import { NextIntlClientProvider } from 'next-intl';

import { ThemeProvider } from '@/components/ThemeProvider';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages();

  return (
    <ClerkProvider>
      <html lang={locale || 'en'}>
        <NextIntlClientProvider messages={messages}>
          <body className={`${inter.className} background`}>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <header>
                {/* Update to use proper sign in page */}
                <SignedOut>
                  <SignInButton />
                </SignedOut>
                <SignedIn>
                  <UserButton />
                </SignedIn>
              </header>
              {children}
            </ThemeProvider>
          </body>
        </NextIntlClientProvider>
      </html>
    </ClerkProvider>
  );
}
